[package]
name = "gesto"
version = "0.1.0"
edition = "2021"

[dependencies]
cortex-m = "0.7"
cortex-m-rt = "0.7"
stm32f4xx-hal = { version = "0.22.1", features = ["stm32f407"] }
panic-halt = "0.2"

[build-dependencies]
cc = "1.0"

[profile.release]
panic = "abort"
