[build]
target = "thumbv7em-none-eabihf"

[target.thumbv7em-none-eabihf]
rustflags = [
    "-Clinker=rust-lld",
    "-Clink-arg=-Tlink.x",
    "-Clink-arg=-Map=firmware.map",
    "-Clink-arg=--print-memory-usage",
]
